### [POST] Izveido kursa autoru
POST http://localhost:8080/api/course-authors
Content-Type: application/json

{
  "course": { "id": "38769e2d-6ada-4749-9dde-18f699340d83" },
  "user": { "id": 1 },
  "role": "galvenais"
}

###

### [GET] Iegūst visus kursa autorus
GET http://localhost:8080/api/course-authors

###

### [PUT] Atjauno autoru ar ID = 1
PUT http://localhost:8080/api/course-authors/1
Content-Type: application/json

{
  "course": { "id": "38769e2d-6ada-4749-9dde-18f699340d83" },
  "user": { "id": 1 },
  "role": "līdzautors"
}

###

### [DELETE] Dzēš autoru ar ID = 1
DELETE http://localhost:8080/api/course-authors/1
