### SESSION TYPES

### Iegūst visus sesiju veidus
GET http://localhost:8080/api/session-types
Accept: application/json

###

### Izveido jaunu sesiju veidu
POST http://localhost:8080/api/session-types
Content-Type: application/json

{
  "name": "Lekcija",
  "description": "Teorētiska nodarbība"
}

###

### Atjauno sesiju veidu
PUT http://localhost:8080/api/session-types/1
Content-Type: application/json

{
  "name": "Seminārs",
  "description": "Diskusiju formāts"
}

###

### Dzēš sesiju veidu
DELETE http://localhost:8080/api/session-types/2

###

### CALENDAR TOPICS

### Iegūst visas kalendāra tēmas
GET http://localhost:8080/api/calendar-topics
Accept: application/json

###

### Izveido tēmu kalendārā
POST http://localhost:8080/api/calendar-topics
Content-Type: application/json

{
  "courseInfo": {
    "id": "6c13ef60-2f56-45be-b2ab-fcec4113b74e"
  },
  "courseContent": {
    "id": 2
  },
  "sequenceNumber": 1,
  "note": "Šī tēma jāmāca otrajā nedēļā",
  "language": "lv"
}

###

### Atjauno kalendāra tēmu
PUT http://localhost:8080/api/calendar-topics/1
Content-Type: application/json

{
  "courseInfo": {
    "id": "6c13ef60-2f56-45be-b2ab-fcec4113b74e"
  },
  "courseContent": {
    "id": 2
  },
  "sequenceNumber": 2,
  "note": "Pārcelta uz 3. nedēļu",
  "language": "lv"
}

###

### Dzēš tēmu no kalendāra
DELETE http://localhost:8080/api/calendar-topics/1

###

### CALENDAR SESSIONS

### Iegūst visas nodarbības
GET http://localhost:8080/api/calendar-sessions
Accept: application/json

###

### Izveido nodarbību
POST http://localhost:8080/api/calendar-sessions
Content-Type: application/json

{
  "topic": {
    "id": 2
  },
  "sessionType": {
    "id": 2
  },
  "academicHours": 2
}

###

### Atjauno nodarbību
PUT http://localhost:8080/api/calendar-sessions/1
Content-Type: application/json

{
  "topic": {
    "id": 2
  },
  "sessionType": {
    "id": 2
  },
  "academicHours": 3
}

###

### Dzēš nodarbību
DELETE http://localhost:8080/api/calendar-sessions/1
