### Iegūst visus priekšnosacījumus
GET http://localhost:8080/api/course-prerequisites
Accept: application/json

###

### Iegūst konkrētu priekšnosacījumu pēc ID
GET http://localhost:8080/api/course-prerequisites/1
Accept: application/json

###

### Izveido jaunu priekšnosacījumu
POST http://localhost:8080/api/course-prerequisites
Content-Type: application/json

{
  "courseInfo": {
    "id": "6c13ef60-2f56-45be-b2ab-fcec4113b74e"
  },
  "requiredCourse": {
    "id": "0fdbf7b1-47c2-45eb-8fcf-e8382e1c3831"
  },
  "type": "required"
}

###

### Atjauno priekšnosacījumu
PUT http://localhost:8080/api/course-prerequisites/1
Content-Type: application/json

{
  "courseInfo": {
    "id": "6c13ef60-2f56-45be-b2ab-fcec4113b74e"
  },
  "requiredCourse": {
    "id": "0fdbf7b1-47c2-45eb-8fcf-e8382e1c3831"
  },
  "type": "recommended"
}

###

### Dzēš priekšnosacījumu
DELETE http://localhost:8080/api/course-prerequisites/1
