### GET all self-study activities
GET http://localhost:8080/api/self-study-activities
Accept: application/json

###

### CREATE activity
POST http://localhost:8080/api/self-study-activities
Content-Type: application/json

{
  "name": "Referāts",
  "description": "Rakstisks analītisks darbs par konkrētu tēmu"
}

###

### UPDATE activity
PUT http://localhost:8080/api/self-study-activities/1
Content-Type: application/json

{
  "name": "Projekts",
  "description": "Komandas darbs reālā problēmu risināšanā"
}

###

### DELETE activity
DELETE http://localhost:8080/api/self-study-activities/2

###

### GET all self-study distributions
GET http://localhost:8080/api/self-study-distribution
Accept: application/json

###

### CREATE distribution
POST http://localhost:8080/api/self-study-distribution
Content-Type: application/json

{
  "courseInfo": {
    "id": "6c13ef60-2f56-45be-b2ab-fcec4113b74e"
  },
  "activity": {
    "id": 2
  },
  "percentage": 40
}

###

### UPDATE distribution
PUT http://localhost:8080/api/self-study-distribution/1
Content-Type: application/json

{
  "courseInfo": {
    "id": "6c13ef60-2f56-45be-b2ab-fcec4113b74e"
  },
  "activity": {
    "id": 2
  },
  "percentage": 60
}

###

### DELETE distribution
DELETE http://localhost:8080/api/self-study-distribution/1
