### Izveido jaunu kursu
POST http://localhost:8080/api/courses
Content-Type: application/json

{
  "courseCode": "ITF120",
  "titleLv": "Programmēšana Java",
  "titleEn": "Java programming",
  "slug": "java",
  "credits": 4,
  "archived": false,
  "active": true
}

### Iegūst visus kursus
GET http://localhost:8080/api/courses

### Iegūst vienu kursu pēc ID
GET http://localhost:8080/api/courses/19936163-7e55-4f60-9506-3eb354f7273d

### Atjauno esošu kursu pēc ID
PUT http://localhost:8080/api/courses/19936163-7e55-4f60-9506-3eb354f7273d
Content-Type: application/json

{
  "courseCode": "ITF123-NEW",
  "titleLv": "Programmēšanas pamati (papildināts)",
  "titleEn": "Intro to Programming - Updated",
  "slug": "programmesana-updated",
  "credits": 6,
  "archived": false,
  "active": true,
  "deletedAt": null
}

### Mīkstā dzēšana (soft delete)
DELETE http://localhost:8080/api/courses/19936163-7e55-4f60-9506-3eb354f7273d

### Iegūst tikai aktīvos (neizdzēstos) kursus
GET http://localhost:8080/api/courses/filter/active

