server.port=8080

##spring.datasource.url=jdbc:postgresql://postgres-db:5432/course_catalog
spring.datasource.url=jdbc:postgresql://localhost:5432/course_catalog
spring.datasource.username=user
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.springframework=DEBUG
logging.level.lv.venta=DEBUG
logging.level.org.hibernate=ERROR